packages:
  - 'gh-cli'
  - 'chrome-extension-wxt'
  - 'skill-finder'
  - 'cloudflare-workers'
  - 'skill-factory'
  - 'uv-ruff-python-tools'
  - 'solana'
  - 'styling-with-tailwind'
  - 'tanstack-query'
